# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
environment:
  VERSION: 1.0.0
  COMMIT: %CIRCLE_SHA1%

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: make build
      - run: C:\Users\circleci\project\main.exe
