name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths-ignore: 
      - "*.md"
      - "docs/**"

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
   
#       - name: Install libyara
#         shell: bash          
#         run: |
#             git clone https://github.com/VirusTotal/yara.git
#             cd yara
#             ./configure
#             make
#             make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache yara
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg
          key: ${{ runner.os }}-yara1
          restore-keys: |
             ${{ runner.os }}-yara1
      # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
#       - name: Install yara
#         shell: bash
#         run: |
#           vcpkg integrate install
#           vcpkg install yara
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            git
      - name: Install libyara
        shell: msys2 {0}           
        run: |
            git clone --depth 1 --branch v4.0.2 https://github.com/VirusTotal/yara.git
            cd yara
            autoreconf -fiv
            ./configure --host=x86_64-w64-mingw32
            make install
      - name: Check goyara
        shell: bash
        run: |
          export PATH=/c/msys64/mingw64/bin:$PATH
          git clone https://github.com/hillu/go-yara.git
          cd go-yara
          go build -ldflags '-extldflags "-static"' -tags yara_static -o simple-yara-w64.exe ./_examples/simple-yara
          ./simple-yara-w64.exe -h
      - name: Compile
        shell: bash
        run: |
          export PATH=/c/msys64/mingw64/bin:$PATH
          export PKG_CONFIG_PATH=$(pwd)
          ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
          go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
          ./main.exe
          
