name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths-ignore: 
      - "*.d"
      - "docs/**"

env:
  VERSION: 1.0.0
           
jobs:
  lint:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
         release: false
         install: >-
           base-devel
           mingw-w64-x86_64-gcc
      - name: Make Python symlink
        shell: bash
        run: |
          ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
          echo "PKG_CONFIG_PATH=$(pwd)" >> $GITHUB_ENV
          export PATH="C:/msys64/mingw64/bin:/d/a/_temp/msys:/c/Users/runneradmin/bin:/c/Users/runneradmin/go/bin:/c/hostedtoolcache/windows/go/1.15.6/x64/bin:/c/Users/runneradmin/.dotnet/tools:/c/Program Files/MongoDB/Server/4.4/bin:/c/aliyun-cli:/c/ProgramData/kind:/c/vcpkg:/c/cf-cli:/c/Program Files (x86)/NSIS:/c/Program Files/Mercurial:/c/hostedtoolcache/windows/stack/2.5.1/x64:/c/ProgramData/chocolatey/lib/ghc.8.10.2.2/tools/ghc-8.10.2/bin:/c/Program Files/dotnet:/c/mysql-5.7.21-winx64/bin:/c/Program Files/R/R-4.0.3/bin/x64:/c/SeleniumWebDrivers/GeckoDriver:/c/Program Files (x86)/sbt/bin:/c/Rust/.cargo/bin:/c/Program Files (x86)/GitHub CLI:/bin:/c/Program Files (x86)/pipx_bin:/c/hostedtoolcache/windows/go/1.14.13/x64/bin:/c/hostedtoolcache/windows/Python/3.7.9/x64/Scripts:/c/hostedtoolcache/windows/Python/3.7.9/x64:/c/hostedtoolcache/windows/Ruby/2.5.8/x64/bin:/c/Program Files/Java/jdk8u275-b01/bin:/c/npm/prefix:/c/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI:/c/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/windows/System32/OpenSSH:/c/ProgramData/Chocolatey/bin:/c/Program Files/Microsoft/Web Platform Installer:/c/Program Files/Docker:/c/Program Files/PowerShell/7:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/nodejs:/c/ProgramData/chocolatey/lib/pulumi/tools/Pulumi/bin:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin:/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code:/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager:/c/Program Files/OpenSSL/bin:/cmd:/mingw64/bin:/usr/bin:/c/tools/php:/c/Program Files (x86)/sbt/bin:/c/Program Files/TortoiseSVN/bin:/c/SeleniumWebDrivers/ChromeDriver:/c/SeleniumWebDrivers/EdgeDriver:/c/Program Files/CMake/bin:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/Amazon/SessionManagerPlugin/bin:/c/Program Files/Amazon/AWSSAMCLI/bin:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files (x86)/Microsoft BizTalk Server:/c/Users/runneradmin/AppData/Local/Microsoft/WindowsApps"
      - name: Echo envs
        shell: bash
        run: |
          echo $PATH
          echo "**********************************"
          echo $PKG_CONFIG_PATH
      - name: Build
        shell: bash
        run: |
          go build main.go
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
     
#   build:
#       runs-on: windows-latest
#       steps:
#       - name: Install Go
#         uses: actions/setup-go@v2
#         with:
#            go-version: 1.15.x
   
# #       - name: Install libyara
# #         shell: bash          
# #         run: |
# #             git clone https://github.com/VirusTotal/yara.git
# #             cd yara
# #             ./configure
# #             make
# #             make install
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup msys2
#         uses: msys2/setup-msys2@v2
#         with:
#           release: false
#           install: >-
#             base-devel
#             mingw-w64-x86_64-gcc
#             git
#       - name: Cache yara
#         uses: actions/cache@v2
#         id: cache
#         with:
#           path: | 
#             **/yara
#           key: ${{ runner.os }}-yara4
#           restore-keys: |
#              ${{ runner.os }}-yara4: 
#       - name: Clone libyara
#         if: steps.cache.outputs.cache-hit != 'true'
#         shell: bash
#         run:  git clone --depth 1 --branch v4.0.2 https://github.com/VirusTotal/yara.git
#       - name: Configure libyara
#         if: steps.cache.outputs.cache-hit != 'true'
#         shell: msys2 {0}           
#         run: |
#             cd yara
#             autoreconf -fiv
#             ./configure --host=x86_64-w64-mingw32
#       - name: Install libyara
#         shell: msys2 {0}           
#         run: |
#             pwd
#             ls -l $(pwd)
#             cd yara
#             make install
#       - name: Check goyara
#         shell: bash
#         run: |
#           export PATH=/c/msys64/mingw64/bin:$PATH
#           git clone https://github.com/hillu/go-yara.git
#           cd go-yara
#           go build -ldflags '-extldflags "-static"' -tags yara_static -o simple-yara-w64.exe ./_examples/simple-yara
#           ./simple-yara-w64.exe -h
#       - name: Compile
#         shell: bash
#         run: |
#           export PATH=/c/msys64/mingw64/bin:$PATH
#           export PKG_CONFIG_PATH=$(pwd)
#           ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
#           go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
#           ./main.exe
#       - uses: actions/upload-artifact@v2
#         with:
#           name: "Main Go"
#           path: "./main.exe"
          
