name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths-ignore: 
      - "*.md"
      - "docs/**"

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            git
      - name: Install libyara
        shell: msys2 {0}           
        run: |
            git clone https://github.com/VirusTotal/yara.git
            cd yara
            autoreconf -fiv
            ./configure --host=x86_64-w64-mingw32
            make install
      - name: Cache libyara
        uses: actions/cache@v2
        with: 
          path: |
            **/mingw64/lib/libyara.a
          key: ${{ runner.os }}-${{ hashFiles('main.go') }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export PATH="c/msys64/mingw64/bin:/c/Strawberry/perl/bin:$PATH"
          export PKG_CONFIG_PATH=$(pwd)
          ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
          go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
          ./main.exe
      - name: Test
        shell: bash
        run: |
          go version
          
