name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
          main.exe
