name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
#       - name: Install libyara
#         uses: msys2/setup-msys2@v2
#         with:
#           install: >-
#             base-devel
#             mingw-w64-x86_64-gcc
#             git
#       - shell: msys2 {0}           
#         run: |
#             git clone https://github.com/VirusTotal/yara.git
#             cd yara
#             autoreconf -fiv
#             ./configure --host=x86_64-w64-mingw32
#             make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          export PATH="c/msys64/mingw64/bin:/c/Strawberry/perl/bin:$PATH"
          export CC="gcc"
          export PKG_CONFIG_PATH=$(pwd)
          go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
          ./main.exe
