name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths-ignore: 
      - "*.md"
      - "docs/**"

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
#       - name: Install libyara
#         shell: bash          
#         run: |
#             git clone https://github.com/VirusTotal/yara.git
#             cd yara
#             ./configure
#             make
#             make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache yara
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg
          key: ${{ runner.os }}
          restore-keys: |
             ${{ runner.os }}-
      # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
      - name: Install yara
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          vcpkg install yara
          ls -l $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE/vcpkg
#       - name: Compile
#         shell: bash
#         run: |
#           export PATH="c/Strawberry/perl/bin:$PATH"
#           export PKG_CONFIG_PATH=$(pwd)
#           ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
#           go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
#           ./main.exe
          
