name: Master build

on:
  pull_request: {}
  push:
    branches:
      - master
      - main
    paths-ignore: 
      - "*.md"
      - "docs/**"

env:
  VERSION: 1.0.0
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
      - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v6
        with:
           # Location of the vcpkg as submodule of the repository.
           vcpkgDirectory: '${{ github.workspace }}/vcpkg'
           setupOnly: true
      - name: Install yara
        run: |
          $VCPKG_ROOT/vcpkg install yara
        shell: bash
#       - name: Install libyara
#         shell: bash          
#         run: |
#             git clone https://github.com/VirusTotal/yara.git
#             cd yara
#             ./configure
#             make
#             make install
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Compile
#         shell: bash
#         run: |
#           export PATH="c/Strawberry/perl/bin:$PATH"
#           export PKG_CONFIG_PATH=$(pwd)
#           ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
#           go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
#           ./main.exe
          
