on:
  push:
    tags:
      - 'v*'
      
name: Upload release

jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        shell: bash
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Adjust pkg-config prefix
        shell: bash
        run: |
           sed -i 's/C:\/Python37/C:\/hostedtoolcache\/windows\/Python\/3.7.9\/x64/' python-37.pc
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
         release: false
         install: >-
           base-devel
           mingw-w64-x86_64-gcc
      - name: Build
        shell: bash
        run: |
          export PATH=/c/msys64/mingw64/bin:$PATH
          export PKG_CONFIG_PATH=$(pwd)
          export VERSION=${{ steps.get_version.outputs.VERSION }}
          go build -ldflags "-s -w -X main.version=$VERSION -X main.commit=$GITHUB_SHA" -o main.exe main.go
          ./main.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
             main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
